/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralabtest.schemas.record.impl.trans;

import de.uni_koblenz.jgralab.impl.GraphFactoryImpl;

import de.uni_koblenz.jgralab.ImplementationType;

import de.uni_koblenz.jgralabtest.schemas.record.RecordTestGraphFactory;

public class RecordTestGraphFactoryImpl extends GraphFactoryImpl implements RecordTestGraphFactory {

	public RecordTestGraphFactoryImpl() {
		super(de.uni_koblenz.jgralabtest.schemas.record.RecordTestSchema.instance(), ImplementationType.TRANSACTION);
		createMaps();
		setGraphImplementationClass(de.uni_koblenz.jgralabtest.schemas.record.RecordTestGraph.GC, de.uni_koblenz.jgralabtest.schemas.record.impl.trans.RecordTestGraphImpl.class);
		setVertexImplementationClass(de.uni_koblenz.jgralabtest.schemas.record.Node.VC, de.uni_koblenz.jgralabtest.schemas.record.impl.trans.NodeImpl.class);
		setEdgeImplementationClass(de.uni_koblenz.jgralabtest.schemas.record.Link.EC, de.uni_koblenz.jgralabtest.schemas.record.impl.trans.LinkImpl.class);
	}
}
