/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralabtest.schemas.gretl.pddsl;

import de.uni_koblenz.jgralab.EdgeDirection;

public interface Chassis extends de.uni_koblenz.jgralabtest.schemas.gretl.pddsl.Element {

	public static final de.uni_koblenz.jgralab.schema.VertexClass VC = de.uni_koblenz.jgralabtest.schemas.gretl.pddsl.PddslSchema.instance().vc_Chassis;

	/**
	 * @return the next de.uni_koblenz.jgralabtest.schemas.gretl.pddsl.Chassis vertex in the global vertex sequence
	 */
	public de.uni_koblenz.jgralabtest.schemas.gretl.pddsl.Chassis getNextChassis();

	/**
	 * @return the next de.uni_koblenz.jgralabtest.schemas.gretl.pddsl.Element vertex in the global vertex sequence
	 */
	public de.uni_koblenz.jgralabtest.schemas.gretl.pddsl.Element getNextElement();

	/**
	 * @return the first edge of class HasConfig at this vertex
	 */
	public de.uni_koblenz.jgralabtest.schemas.gretl.pddsl.HasConfig getFirstHasConfigIncidence();

	/**
	 * @return the first edge of class HasConfig at this vertex
	 * @param orientation the orientation of the edge
	 */
	public de.uni_koblenz.jgralabtest.schemas.gretl.pddsl.HasConfig getFirstHasConfigIncidence(EdgeDirection orientation);
		/**
		 * adds the given vertex as <code>config</code> to this vertex, i.e. creates an
		 * <code>de.uni_koblenz.jgralabtest.schemas.gretl.pddsl.HasConfig</code> edge from this vertex to the given 
		 * one and returns the created edge.
		 * @return  a newly created edge of type <code>de.uni_koblenz.jgralabtest.schemas.gretl.pddsl.HasConfig</code>
		 *          between this vertex and the given one.
		 */
		public de.uni_koblenz.jgralabtest.schemas.gretl.pddsl.HasConfig add_config(de.uni_koblenz.jgralabtest.schemas.gretl.pddsl.Configuration vertex);
		/**
		 * removes all config adjacences to all vertices by 
		 * deleting the <code>de.uni_koblenz.jgralabtest.schemas.gretl.pddsl.HasConfig</code> edges of this vertex to 
		 * all other ones, but doesn't delete those vertices.
		 *
		 * @return the adjacent vertices prior to removal of incidences
		 */
		public java.util.List<? extends de.uni_koblenz.jgralabtest.schemas.gretl.pddsl.Configuration> remove_config();
		/**
		 * removes the given vertex as <code>config</code> from this vertex, i.e. 
		 * deletes the <code>de.uni_koblenz.jgralabtest.schemas.gretl.pddsl.HasConfig</code> edge connections of this vertex with 
		 * the given one.
		 */
		public boolean remove_config(de.uni_koblenz.jgralabtest.schemas.gretl.pddsl.Configuration vertex);
		/**
		 * @return the vertex to this one with the rolename 'config' 
		 *         (connected with a <code>de.uni_koblenz.jgralabtest.schemas.gretl.pddsl.HasConfig</code> edge), or null if no such vertex exists
		 */
		public de.uni_koblenz.jgralabtest.schemas.gretl.pddsl.Configuration get_config();

	/**
	 * Returns an Iterable for all incidence edges of this vertex that are of type HasConfig or subtypes.
	 */
	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.pddsl.HasConfig> getHasConfigIncidences();
	
	/**
	 * Returns an Iterable for all incidence edges of this vertex that are of type HasConfig.
	 * @param direction EdgeDirection.IN or EdgeDirection.OUT, only edges of this direction will be included in the Iterable
	 */
	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.pddsl.HasConfig> getHasConfigIncidences(EdgeDirection direction);
}
