/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralabtest.schemas.eca.simplelibrary.impl.std;

import de.uni_koblenz.jgralab.impl.std.ReversedEdgeImpl;
import de.uni_koblenz.jgralab.impl.std.EdgeImpl;

import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.Graph;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;

import de.uni_koblenz.jgralabtest.schemas.eca.simplelibrary.Medium;
import de.uni_koblenz.jgralabtest.schemas.eca.simplelibrary.User;

import java.io.IOException;

public class ReversedLoansImpl extends ReversedEdgeImpl implements de.uni_koblenz.jgralab.Edge, de.uni_koblenz.jgralabtest.schemas.eca.simplelibrary.Loans {

	ReversedLoansImpl(EdgeImpl e, Graph g) {
		super(e, g);
	}

	@Override
	public final de.uni_koblenz.jgralab.schema.EdgeClass getAttributedElementClass() {
		return getNormalEdge().getAttributedElementClass();
	}

	public de.uni_koblenz.jgralabtest.schemas.eca.simplelibrary.Date get_date() {
		return ((de.uni_koblenz.jgralabtest.schemas.eca.simplelibrary.Loans)normalEdge).get_date();
	}

	public void set_date(de.uni_koblenz.jgralabtest.schemas.eca.simplelibrary.Date _date) {
		((de.uni_koblenz.jgralabtest.schemas.eca.simplelibrary.Loans)normalEdge).set_date(_date);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
		throw new GraphIOException("Can not call readAttributeValues for reversed Edges.");
	}

	public void readAttributeValueFromString(String attributeName, String value) throws GraphIOException {
		throw new GraphIOException("Can not call readAttributeValuesFromString for reversed Edges.");
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
		throw new GraphIOException("Can not call writeAttributeValues for reversed Edges.");
	}

	public String writeAttributeValueToString(String _attributeName) throws IOException, GraphIOException {
		throw new GraphIOException("Can not call writeAttributeValueToString for reversed Edges.");
	}

	public de.uni_koblenz.jgralabtest.schemas.eca.simplelibrary.Loans getNextLoansInGraph() {
		return ((de.uni_koblenz.jgralabtest.schemas.eca.simplelibrary.Loans)normalEdge).getNextLoansInGraph();
	}

	public de.uni_koblenz.jgralabtest.schemas.eca.simplelibrary.Loans getNextLoansIncidence() {
		return (de.uni_koblenz.jgralabtest.schemas.eca.simplelibrary.Loans)getNextIncidence(de.uni_koblenz.jgralabtest.schemas.eca.simplelibrary.Loans.class);
	}

	public de.uni_koblenz.jgralabtest.schemas.eca.simplelibrary.Loans getNextLoansIncidence(EdgeDirection orientation) {
		return (de.uni_koblenz.jgralabtest.schemas.eca.simplelibrary.Loans)getNextIncidence(de.uni_koblenz.jgralabtest.schemas.eca.simplelibrary.Loans.class, orientation);
	}
	public User getAlpha() {
		return (User) super.getAlpha();
	}
	public Medium getOmega() {
		return (Medium) super.getOmega();
	}
}
