/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralabtest.schemas.vertextest.impl.db;

import de.uni_koblenz.jgralab.impl.db.EdgeImpl;

import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;
import de.uni_koblenz.jgralab.NoSuchAttributeException;
import de.uni_koblenz.jgralab.Vertex;

import de.uni_koblenz.jgralabtest.schemas.vertextest.impl.db.ReversedKImpl;

import de.uni_koblenz.jgralabtest.schemas.vertextest.A;
import de.uni_koblenz.jgralabtest.schemas.vertextest.B;

import java.io.IOException;
/**
 * FromVertexClass: A
 * FromRoleName : sourceK
 * ToVertexClass: B
 * ToRoleName : targetK
 */

public class KImpl extends EdgeImpl implements de.uni_koblenz.jgralabtest.schemas.vertextest.H, de.uni_koblenz.jgralabtest.schemas.vertextest.K {

	public KImpl(int id, de.uni_koblenz.jgralab.Graph g, Vertex alpha, Vertex omega) {
		super(id, g, alpha, omega);
	}

	@Override
	public final de.uni_koblenz.jgralab.schema.EdgeClass getAttributedElementClass() {
		return de.uni_koblenz.jgralabtest.schemas.vertextest.K.EC;
	}

	@Override
	public final java.lang.Class<? extends de.uni_koblenz.jgralab.Edge> getSchemaClass() {
		return de.uni_koblenz.jgralabtest.schemas.vertextest.K.class;
	}

	public <T> T getAttribute(String attributeName) {
		throw new NoSuchAttributeException("K doesn't contain an attribute " + attributeName);
	}

	public <T> void setAttribute(String attributeName, T data) {
		throw new NoSuchAttributeException("K doesn't contain an attribute " + attributeName);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void readAttributeValueFromString(String attributeName, String value) throws GraphIOException {
		throw new NoSuchAttributeException("K doesn't contain an attribute " + attributeName);
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public String writeAttributeValueToString(String attributeName) throws IOException, GraphIOException {
		throw new NoSuchAttributeException("K doesn't contain an attribute " + attributeName);
	}

	public de.uni_koblenz.jgralabtest.schemas.vertextest.E getNextEInGraph() {
		return (de.uni_koblenz.jgralabtest.schemas.vertextest.E)getNextEdge(de.uni_koblenz.jgralabtest.schemas.vertextest.E.class);
	}

	public de.uni_koblenz.jgralabtest.schemas.vertextest.H getNextHInGraph() {
		return (de.uni_koblenz.jgralabtest.schemas.vertextest.H)getNextEdge(de.uni_koblenz.jgralabtest.schemas.vertextest.H.class);
	}

	public de.uni_koblenz.jgralabtest.schemas.vertextest.K getNextKInGraph() {
		return (de.uni_koblenz.jgralabtest.schemas.vertextest.K)getNextEdge(de.uni_koblenz.jgralabtest.schemas.vertextest.K.class);
	}

	public de.uni_koblenz.jgralabtest.schemas.vertextest.E getNextEIncidence() {
		return (de.uni_koblenz.jgralabtest.schemas.vertextest.E)getNextIncidence(de.uni_koblenz.jgralabtest.schemas.vertextest.E.class);
	}

	public de.uni_koblenz.jgralabtest.schemas.vertextest.E getNextEIncidence(EdgeDirection orientation) {
		return (de.uni_koblenz.jgralabtest.schemas.vertextest.E)getNextIncidence(de.uni_koblenz.jgralabtest.schemas.vertextest.E.class, orientation);
	}

	public de.uni_koblenz.jgralabtest.schemas.vertextest.H getNextHIncidence() {
		return (de.uni_koblenz.jgralabtest.schemas.vertextest.H)getNextIncidence(de.uni_koblenz.jgralabtest.schemas.vertextest.H.class);
	}

	public de.uni_koblenz.jgralabtest.schemas.vertextest.H getNextHIncidence(EdgeDirection orientation) {
		return (de.uni_koblenz.jgralabtest.schemas.vertextest.H)getNextIncidence(de.uni_koblenz.jgralabtest.schemas.vertextest.H.class, orientation);
	}

	public de.uni_koblenz.jgralabtest.schemas.vertextest.K getNextKIncidence() {
		return (de.uni_koblenz.jgralabtest.schemas.vertextest.K)getNextIncidence(de.uni_koblenz.jgralabtest.schemas.vertextest.K.class);
	}

	public de.uni_koblenz.jgralabtest.schemas.vertextest.K getNextKIncidence(EdgeDirection orientation) {
		return (de.uni_koblenz.jgralabtest.schemas.vertextest.K)getNextIncidence(de.uni_koblenz.jgralabtest.schemas.vertextest.K.class, orientation);
	}

	public de.uni_koblenz.jgralab.schema.AggregationKind getAggregationKind() {
		return de.uni_koblenz.jgralab.schema.AggregationKind.NONE;
	}

	@Override
	public de.uni_koblenz.jgralab.schema.AggregationKind getAlphaAggregationKind() {
		return de.uni_koblenz.jgralab.schema.AggregationKind.NONE;
	}

	@Override
	public de.uni_koblenz.jgralab.schema.AggregationKind getOmegaAggregationKind() {
		return de.uni_koblenz.jgralab.schema.AggregationKind.NONE;
	}

	protected de.uni_koblenz.jgralab.impl.ReversedEdgeBaseImpl createReversedEdge() {
		return new ReversedKImpl(this, graph);
	}
	public A getAlpha() {
		return (A) super.getAlpha();
	}
	public B getOmega() {
		return (B) super.getOmega();
	}
}
