/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralabtest.schemas.motorwaymap;

import de.uni_koblenz.jgralab.EdgeDirection;

import de.uni_koblenz.jgralabtest.schemas.motorwaymap.City;
import de.uni_koblenz.jgralabtest.schemas.motorwaymap.Motorway;
/**
 * FromVertexClass: City
 * FromRoleName : 
 * ToVertexClass: Motorway
 * ToRoleName : 
 */

public interface Exit extends de.uni_koblenz.jgralab.Edge {

	public static final de.uni_koblenz.jgralab.schema.EdgeClass EC = de.uni_koblenz.jgralabtest.schemas.motorwaymap.MotorwayMapSchema.instance().ec_Exit;

	public int get_number();

	public void set_number(int _number);

	/**
	 * @return the next de.uni_koblenz.jgralabtest.schemas.motorwaymap.Exit edge in the global edge sequence
	 */
	public de.uni_koblenz.jgralabtest.schemas.motorwaymap.Exit getNextExitInGraph();

	/**
	 * @return the next edge of class de.uni_koblenz.jgralabtest.schemas.motorwaymap.Exit at the "this" vertex
	 */
	public de.uni_koblenz.jgralabtest.schemas.motorwaymap.Exit getNextExitIncidence();

	/**
	 * @return the next edge of class de.uni_koblenz.jgralabtest.schemas.motorwaymap.Exit at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public de.uni_koblenz.jgralabtest.schemas.motorwaymap.Exit getNextExitIncidence(EdgeDirection orientation);
	public City getAlpha();
	public Motorway getOmega();
}
