/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralabtest.schemas.motorwaymap;

public enum TestEnum {

	Test1, Test2, Test3;

	public static TestEnum valueOfPermitNull(String val) {
		if (val.equals(de.uni_koblenz.jgralab.GraphIO.NULL_LITERAL)) {
			return null;
		}
		return valueOf(val);
	}
}
