/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralabtest.schemas.gretl.varro.impl.std;

import de.uni_koblenz.jgralab.impl.EdgeIterable;
import de.uni_koblenz.jgralab.impl.VertexIterable;

import de.uni_koblenz.jgralab.impl.std.GraphImpl;

import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;
import de.uni_koblenz.jgralab.NoSuchAttributeException;
import de.uni_koblenz.jgralab.Vertex;
import de.uni_koblenz.jgralab.greql2.evaluator.GreqlEvaluator;

import java.io.IOException;

import org.pcollections.POrderedSet;

public class UMLGraphImpl extends GraphImpl implements de.uni_koblenz.jgralab.Graph, de.uni_koblenz.jgralabtest.schemas.gretl.varro.UMLGraph {

	/**
	 * DON'T USE THE CONSTRUCTOR
	 * For instantiating a Graph, use the Schema and a GraphFactory
	**/
	public UMLGraphImpl() {
		this(null);
	}
	
	/**
	 * DON'T USE THE CONSTRUCTOR
	 * For instantiating a Graph, use the Schema and a GraphFactory
	**/
	public UMLGraphImpl(int vMax, int eMax) {
		this(null, vMax, eMax);
	}
	
	/**
	 * DON'T USE THE CONSTRUCTOR
	 * For instantiating a Graph, use the Schema and a GraphFactory
	**/
	public UMLGraphImpl(java.lang.String id, int vMax, int eMax) {
		super(id, de.uni_koblenz.jgralabtest.schemas.gretl.varro.UMLGraph.GC, vMax, eMax);
		initializeAttributesWithDefaultValues();
	}
	
	/**
	 * DON'T USE THE CONSTRUCTOR
	 * For instantiating a Graph, use the Schema and a GraphFactory
	**/
	public UMLGraphImpl(java.lang.String id) {
		super(id, de.uni_koblenz.jgralabtest.schemas.gretl.varro.UMLGraph.GC);
		initializeAttributesWithDefaultValues();
	}

	@Override
	public final de.uni_koblenz.jgralab.schema.GraphClass getAttributedElementClass() {
		return de.uni_koblenz.jgralabtest.schemas.gretl.varro.UMLGraph.GC;
	}

	@Override
	public final java.lang.Class<? extends de.uni_koblenz.jgralab.Graph> getSchemaClass() {
		return de.uni_koblenz.jgralabtest.schemas.gretl.varro.UMLGraph.class;
	}

	public <T> T getAttribute(String attributeName) {
		throw new NoSuchAttributeException("UMLGraph doesn't contain an attribute " + attributeName);
	}

	public <T> void setAttribute(String attributeName, T data) {
		throw new NoSuchAttributeException("UMLGraph doesn't contain an attribute " + attributeName);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void readAttributeValueFromString(String attributeName, String value) throws GraphIOException {
		throw new NoSuchAttributeException("UMLGraph doesn't contain an attribute " + attributeName);
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public String writeAttributeValueToString(String attributeName) throws IOException, GraphIOException {
		throw new NoSuchAttributeException("UMLGraph doesn't contain an attribute " + attributeName);
	}
	
	protected GreqlEvaluator greqlEvaluator;

	@Override
	public synchronized <T extends Vertex> POrderedSet<T> reachableVertices(Vertex startVertex, String pathDescription, Class<T> vertexType) {
		if (greqlEvaluator == null) {
			greqlEvaluator = new GreqlEvaluator((String) null, this, null);
		}
		greqlEvaluator.setVariable("v", startVertex);
		greqlEvaluator.setQuery("using v: v " + pathDescription);
		greqlEvaluator.startEvaluation();
		return greqlEvaluator.getResultSet();
	}

	// ------------------------ Code for uml.Assoc ------------------------

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Assoc getFirstAssoc() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Assoc)getFirstVertex(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Assoc.VC);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Assoc createAssoc() {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Assoc> createVertex(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Assoc.VC, 0, this);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Assoc createAssoc(int id) {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Assoc> createVertex(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Assoc.VC, id, this);
	}

	// ------------------------ Code for uml.AssocEnd ------------------------

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.AssocEnd getFirstAssocEnd() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.AssocEnd)getFirstVertex(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.AssocEnd.VC);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.AssocEnd createAssocEnd() {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.AssocEnd> createVertex(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.AssocEnd.VC, 0, this);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.AssocEnd createAssocEnd(int id) {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.AssocEnd> createVertex(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.AssocEnd.VC, id, this);
	}

	// ------------------------ Code for uml.Attribute ------------------------

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute getFirstAttribute() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute)getFirstVertex(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute.VC);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute createAttribute() {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute> createVertex(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute.VC, 0, this);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute createAttribute(int id) {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute> createVertex(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute.VC, id, this);
	}

	// ------------------------ Code for uml.Class ------------------------

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class getFirstClass() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class)getFirstVertex(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class.VC);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class createClass() {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class> createVertex(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class.VC, 0, this);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class createClass(int id) {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class> createVertex(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class.VC, id, this);
	}

	// ------------------------ Code for uml.ContainsAssoc ------------------------

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsAssoc getFirstContainsAssoc() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsAssoc)getFirstEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsAssoc.EC);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsAssoc createContainsAssoc(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package alpha, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Assoc omega) {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsAssoc> createEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsAssoc.EC, 0, this, alpha, omega);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsAssoc createContainsAssoc(int id, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package alpha, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Assoc omega) {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsAssoc> createEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsAssoc.EC, id, this, alpha, omega);
	}

	// ------------------------ Code for uml.ContainsClass ------------------------

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass getFirstContainsClass() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass)getFirstEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass.EC);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass createContainsClass(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package alpha, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class omega) {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass> createEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass.EC, 0, this, alpha, omega);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass createContainsClass(int id, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package alpha, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class omega) {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass> createEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass.EC, id, this, alpha, omega);
	}

	// ------------------------ Code for uml.ContainsGeneral ------------------------

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsGeneral getFirstContainsGeneral() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsGeneral)getFirstEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsGeneral.EC);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsGeneral createContainsGeneral(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package alpha, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.General omega) {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsGeneral> createEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsGeneral.EC, 0, this, alpha, omega);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsGeneral createContainsGeneral(int id, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package alpha, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.General omega) {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsGeneral> createEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsGeneral.EC, id, this, alpha, omega);
	}

	// ------------------------ Code for uml.General ------------------------

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.General getFirstGeneral() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.General)getFirstVertex(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.General.VC);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.General createGeneral() {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.General> createVertex(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.General.VC, 0, this);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.General createGeneral(int id) {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.General> createVertex(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.General.VC, id, this);
	}

	// ------------------------ Code for uml.HasAssocEnd ------------------------

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAssocEnd getFirstHasAssocEnd() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAssocEnd)getFirstEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAssocEnd.EC);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAssocEnd createHasAssocEnd(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Assoc alpha, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.AssocEnd omega) {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAssocEnd> createEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAssocEnd.EC, 0, this, alpha, omega);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAssocEnd createHasAssocEnd(int id, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Assoc alpha, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.AssocEnd omega) {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAssocEnd> createEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAssocEnd.EC, id, this, alpha, omega);
	}

	// ------------------------ Code for uml.HasAttribute ------------------------

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute getFirstHasAttribute() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute)getFirstEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute.EC);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute createHasAttribute(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class alpha, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute omega) {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute> createEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute.EC, 0, this, alpha, omega);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute createHasAttribute(int id, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class alpha, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute omega) {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute> createEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute.EC, id, this, alpha, omega);
	}

	// ------------------------ Code for uml.HasSub ------------------------

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub getFirstHasSub() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub)getFirstEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub.EC);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub createHasSub(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.General alpha, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class omega) {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub> createEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub.EC, 0, this, alpha, omega);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub createHasSub(int id, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.General alpha, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class omega) {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub> createEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub.EC, id, this, alpha, omega);
	}

	// ------------------------ Code for uml.HasSuper ------------------------

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper getFirstHasSuper() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper)getFirstEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper.EC);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper createHasSuper(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.General alpha, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class omega) {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper> createEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper.EC, 0, this, alpha, omega);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper createHasSuper(int id, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.General alpha, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class omega) {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper> createEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper.EC, id, this, alpha, omega);
	}

	// ------------------------ Code for uml.HasType ------------------------

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType getFirstHasType() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType)getFirstEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType.EC);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType createHasType(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.AssocEnd alpha, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class omega) {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType> createEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType.EC, 0, this, alpha, omega);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType createHasType(int id, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.AssocEnd alpha, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class omega) {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType> createEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType.EC, id, this, alpha, omega);
	}

	// ------------------------ Code for uml.NamedElement ------------------------

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.NamedElement getFirstNamedElement() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.NamedElement)getFirstVertex(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.NamedElement.VC);
	}

	// ------------------------ Code for uml.Package ------------------------

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package getFirstPackage() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package)getFirstVertex(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package.VC);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package createPackage() {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package> createVertex(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package.VC, 0, this);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package createPackage(int id) {
		return graphFactory.<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package> createVertex(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package.VC, id, this);
	}

	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsAssoc> getContainsAssocEdges() {
		return new EdgeIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsAssoc>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsAssoc.class);
	}
	

	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAssocEnd> getHasAssocEndEdges() {
		return new EdgeIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAssocEnd>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAssocEnd.class);
	}
	

	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass> getContainsClassEdges() {
		return new EdgeIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass.class);
	}
	

	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType> getHasTypeEdges() {
		return new EdgeIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType.class);
	}
	

	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub> getHasSubEdges() {
		return new EdgeIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub.class);
	}
	

	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper> getHasSuperEdges() {
		return new EdgeIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper.class);
	}
	

	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsGeneral> getContainsGeneralEdges() {
		return new EdgeIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsGeneral>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsGeneral.class);
	}
	

	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute> getHasAttributeEdges() {
		return new EdgeIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute.class);
	}
	

	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.General> getGeneralVertices() {
		return new VertexIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.General>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.General.class);
	}
	

	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.NamedElement> getNamedElementVertices() {
		return new VertexIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.NamedElement>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.NamedElement.class);
	}
	

	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Assoc> getAssocVertices() {
		return new VertexIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Assoc>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Assoc.class);
	}
	

	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.AssocEnd> getAssocEndVertices() {
		return new VertexIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.AssocEnd>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.AssocEnd.class);
	}
	

	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class> getClassVertices() {
		return new VertexIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class.class);
	}
	

	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package> getPackageVertices() {
		return new VertexIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package.class);
	}
	

	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute> getAttributeVertices() {
		return new VertexIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute.class);
	}
	
}
