/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.gretl.template.impl.std;

import de.uni_koblenz.jgralab.impl.EdgeIterable;
import de.uni_koblenz.jgralab.impl.VertexIterable;

import de.uni_koblenz.jgralab.impl.std.GraphImpl;

import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;
import de.uni_koblenz.jgralab.NoSuchAttributeException;
import de.uni_koblenz.jgralab.Vertex;
import de.uni_koblenz.jgralab.greql2.evaluator.GreqlEvaluator;

import java.io.IOException;

import org.pcollections.POrderedSet;

public class TemplateGraphImpl extends GraphImpl implements de.uni_koblenz.jgralab.Graph, de.uni_koblenz.jgralab.gretl.template.TemplateGraph {

	/**
	 * DON'T USE THE CONSTRUCTOR
	 * For instantiating a Graph, use the Schema and a GraphFactory
	**/
	public TemplateGraphImpl() {
		this(null);
	}
	
	/**
	 * DON'T USE THE CONSTRUCTOR
	 * For instantiating a Graph, use the Schema and a GraphFactory
	**/
	public TemplateGraphImpl(int vMax, int eMax) {
		this(null, vMax, eMax);
	}
	
	/**
	 * DON'T USE THE CONSTRUCTOR
	 * For instantiating a Graph, use the Schema and a GraphFactory
	**/
	public TemplateGraphImpl(java.lang.String id, int vMax, int eMax) {
		super(id, de.uni_koblenz.jgralab.gretl.template.TemplateGraph.GC, vMax, eMax);
		initializeAttributesWithDefaultValues();
	}
	
	/**
	 * DON'T USE THE CONSTRUCTOR
	 * For instantiating a Graph, use the Schema and a GraphFactory
	**/
	public TemplateGraphImpl(java.lang.String id) {
		super(id, de.uni_koblenz.jgralab.gretl.template.TemplateGraph.GC);
		initializeAttributesWithDefaultValues();
	}

	@Override
	public final de.uni_koblenz.jgralab.schema.GraphClass getAttributedElementClass() {
		return de.uni_koblenz.jgralab.gretl.template.TemplateGraph.GC;
	}

	@Override
	public final java.lang.Class<? extends de.uni_koblenz.jgralab.Graph> getSchemaClass() {
		return de.uni_koblenz.jgralab.gretl.template.TemplateGraph.class;
	}

	public <T> T getAttribute(String attributeName) {
		throw new NoSuchAttributeException("TemplateGraph doesn't contain an attribute " + attributeName);
	}

	public <T> void setAttribute(String attributeName, T data) {
		throw new NoSuchAttributeException("TemplateGraph doesn't contain an attribute " + attributeName);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void readAttributeValueFromString(String attributeName, String value) throws GraphIOException {
		throw new NoSuchAttributeException("TemplateGraph doesn't contain an attribute " + attributeName);
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public String writeAttributeValueToString(String attributeName) throws IOException, GraphIOException {
		throw new NoSuchAttributeException("TemplateGraph doesn't contain an attribute " + attributeName);
	}
	
	protected GreqlEvaluator greqlEvaluator;

	@Override
	public synchronized <T extends Vertex> POrderedSet<T> reachableVertices(Vertex startVertex, String pathDescription, Class<T> vertexType) {
		if (greqlEvaluator == null) {
			greqlEvaluator = new GreqlEvaluator((String) null, this, null);
		}
		greqlEvaluator.setVariable("v", startVertex);
		greqlEvaluator.setQuery("using v: v " + pathDescription);
		greqlEvaluator.startEvaluation();
		return greqlEvaluator.getResultSet();
	}

	// ------------------------ Code for CreateEdge ------------------------

	public de.uni_koblenz.jgralab.gretl.template.CreateEdge getFirstCreateEdge() {
		return (de.uni_koblenz.jgralab.gretl.template.CreateEdge)getFirstEdge(de.uni_koblenz.jgralab.gretl.template.CreateEdge.EC);
	}

	public de.uni_koblenz.jgralab.gretl.template.CreateEdge createCreateEdge(de.uni_koblenz.jgralab.gretl.template.CreateVertex alpha, de.uni_koblenz.jgralab.gretl.template.CreateVertex omega) {
		return graphFactory.<de.uni_koblenz.jgralab.gretl.template.CreateEdge> createEdge(de.uni_koblenz.jgralab.gretl.template.CreateEdge.EC, 0, this, alpha, omega);
	}

	public de.uni_koblenz.jgralab.gretl.template.CreateEdge createCreateEdge(int id, de.uni_koblenz.jgralab.gretl.template.CreateVertex alpha, de.uni_koblenz.jgralab.gretl.template.CreateVertex omega) {
		return graphFactory.<de.uni_koblenz.jgralab.gretl.template.CreateEdge> createEdge(de.uni_koblenz.jgralab.gretl.template.CreateEdge.EC, id, this, alpha, omega);
	}

	// ------------------------ Code for CreateVertex ------------------------

	public de.uni_koblenz.jgralab.gretl.template.CreateVertex getFirstCreateVertex() {
		return (de.uni_koblenz.jgralab.gretl.template.CreateVertex)getFirstVertex(de.uni_koblenz.jgralab.gretl.template.CreateVertex.VC);
	}

	public de.uni_koblenz.jgralab.gretl.template.CreateVertex createCreateVertex() {
		return graphFactory.<de.uni_koblenz.jgralab.gretl.template.CreateVertex> createVertex(de.uni_koblenz.jgralab.gretl.template.CreateVertex.VC, 0, this);
	}

	public de.uni_koblenz.jgralab.gretl.template.CreateVertex createCreateVertex(int id) {
		return graphFactory.<de.uni_koblenz.jgralab.gretl.template.CreateVertex> createVertex(de.uni_koblenz.jgralab.gretl.template.CreateVertex.VC, id, this);
	}

	public Iterable<de.uni_koblenz.jgralab.gretl.template.CreateEdge> getCreateEdgeEdges() {
		return new EdgeIterable<de.uni_koblenz.jgralab.gretl.template.CreateEdge>(this, de.uni_koblenz.jgralab.gretl.template.CreateEdge.class);
	}
	

	public Iterable<de.uni_koblenz.jgralab.gretl.template.CreateVertex> getCreateVertexVertices() {
		return new VertexIterable<de.uni_koblenz.jgralab.gretl.template.CreateVertex>(this, de.uni_koblenz.jgralab.gretl.template.CreateVertex.class);
	}
	
}
