/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralabtest.schemas.gretl.bedsl.impl.std;

import de.uni_koblenz.jgralab.impl.std.EdgeImpl;

import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;
import de.uni_koblenz.jgralab.NoSuchAttributeException;
import de.uni_koblenz.jgralab.Vertex;

import de.uni_koblenz.jgralabtest.schemas.gretl.bedsl.impl.std.ReversedHasSupertypeImpl;

import de.uni_koblenz.jgralabtest.schemas.gretl.bedsl.Entity;

import java.io.IOException;
/**
 * FromVertexClass: Entity
 * FromRoleName : subType
 * ToVertexClass: Entity
 * ToRoleName : superType
 */

public class HasSupertypeImpl extends EdgeImpl implements de.uni_koblenz.jgralab.Edge, de.uni_koblenz.jgralabtest.schemas.gretl.bedsl.HasSupertype {

	public HasSupertypeImpl(int id, de.uni_koblenz.jgralab.Graph g, Vertex alpha, Vertex omega) {
		super(id, g, alpha, omega);
		((de.uni_koblenz.jgralab.impl.InternalGraph) graph).addEdge(this, alpha, omega);
	}

	@Override
	public final de.uni_koblenz.jgralab.schema.EdgeClass getAttributedElementClass() {
		return de.uni_koblenz.jgralabtest.schemas.gretl.bedsl.HasSupertype.EC;
	}

	@Override
	public final java.lang.Class<? extends de.uni_koblenz.jgralab.Edge> getSchemaClass() {
		return de.uni_koblenz.jgralabtest.schemas.gretl.bedsl.HasSupertype.class;
	}

	public <T> T getAttribute(String attributeName) {
		throw new NoSuchAttributeException("HasSupertype doesn't contain an attribute " + attributeName);
	}

	public <T> void setAttribute(String attributeName, T data) {
		throw new NoSuchAttributeException("HasSupertype doesn't contain an attribute " + attributeName);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void readAttributeValueFromString(String attributeName, String value) throws GraphIOException {
		throw new NoSuchAttributeException("HasSupertype doesn't contain an attribute " + attributeName);
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public String writeAttributeValueToString(String attributeName) throws IOException, GraphIOException {
		throw new NoSuchAttributeException("HasSupertype doesn't contain an attribute " + attributeName);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.bedsl.HasSupertype getNextHasSupertypeInGraph() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.bedsl.HasSupertype)getNextEdge(de.uni_koblenz.jgralabtest.schemas.gretl.bedsl.HasSupertype.class);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.bedsl.HasSupertype getNextHasSupertypeIncidence() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.bedsl.HasSupertype)getNextIncidence(de.uni_koblenz.jgralabtest.schemas.gretl.bedsl.HasSupertype.class);
	}

	public de.uni_koblenz.jgralabtest.schemas.gretl.bedsl.HasSupertype getNextHasSupertypeIncidence(EdgeDirection orientation) {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.bedsl.HasSupertype)getNextIncidence(de.uni_koblenz.jgralabtest.schemas.gretl.bedsl.HasSupertype.class, orientation);
	}

	public de.uni_koblenz.jgralab.schema.AggregationKind getAggregationKind() {
		return de.uni_koblenz.jgralab.schema.AggregationKind.NONE;
	}

	@Override
	public de.uni_koblenz.jgralab.schema.AggregationKind getAlphaAggregationKind() {
		return de.uni_koblenz.jgralab.schema.AggregationKind.NONE;
	}

	@Override
	public de.uni_koblenz.jgralab.schema.AggregationKind getOmegaAggregationKind() {
		return de.uni_koblenz.jgralab.schema.AggregationKind.NONE;
	}

	protected de.uni_koblenz.jgralab.impl.ReversedEdgeBaseImpl createReversedEdge() {
		return new ReversedHasSupertypeImpl(this, graph);
	}
	public Entity getAlpha() {
		return (Entity) super.getAlpha();
	}
	public Entity getOmega() {
		return (Entity) super.getOmega();
	}
}
