/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.impl.std;

import de.uni_koblenz.jgralab.impl.GraphFactoryImpl;

import de.uni_koblenz.jgralab.ImplementationType;

import de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.SimpleUMLGraphFactory;

public class SimpleUMLGraphFactoryImpl extends GraphFactoryImpl implements SimpleUMLGraphFactory {

	public SimpleUMLGraphFactoryImpl() {
		super(de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.SimpleUMLSchema.instance(), ImplementationType.STANDARD);
		createMaps();
		setGraphImplementationClass(de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.SimpleUMLGraph.GC, de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.impl.std.SimpleUMLGraphImpl.class);
		setVertexImplementationClass(de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.Attribute.VC, de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.impl.std.AttributeImpl.class);
		setVertexImplementationClass(de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.Association.VC, de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.impl.std.AssociationImpl.class);
		setVertexImplementationClass(de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.Package.VC, de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.impl.std.PackageImpl.class);
		setVertexImplementationClass(de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.Classifier.VC, de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.impl.std.ClassifierImpl.class);
		setVertexImplementationClass(de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.PrimitiveDataType.VC, de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.impl.std.PrimitiveDataTypeImpl.class);
		setVertexImplementationClass(de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.Class.VC, de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.impl.std.ClassImpl.class);
		setEdgeImplementationClass(de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.HasType.EC, de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.impl.std.HasTypeImpl.class);
		setEdgeImplementationClass(de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.Contains.EC, de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.impl.std.ContainsImpl.class);
		setEdgeImplementationClass(de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.HasSuperclass.EC, de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.impl.std.HasSuperclassImpl.class);
		setEdgeImplementationClass(de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.HasTarget.EC, de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.impl.std.HasTargetImpl.class);
		setEdgeImplementationClass(de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.HasAttribute.EC, de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.impl.std.HasAttributeImpl.class);
		setEdgeImplementationClass(de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.HasSource.EC, de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simpleuml.impl.std.HasSourceImpl.class);
	}
}
