/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralabtest.schemas.defaultvaluetestschema.impl.db;

import de.uni_koblenz.jgralab.impl.GraphFactoryImpl;

import de.uni_koblenz.jgralab.ImplementationType;

import de.uni_koblenz.jgralabtest.schemas.defaultvaluetestschema.DefaultValueTestGraphFactory;

public class DefaultValueTestGraphFactoryImpl extends GraphFactoryImpl implements DefaultValueTestGraphFactory {

	public DefaultValueTestGraphFactoryImpl() {
		super(de.uni_koblenz.jgralabtest.schemas.defaultvaluetestschema.DefaultValueTestSchema.instance(), ImplementationType.DATABASE);
		createMaps();
		setGraphImplementationClass(de.uni_koblenz.jgralabtest.schemas.defaultvaluetestschema.DefaultValueTestGraph.GC, de.uni_koblenz.jgralabtest.schemas.defaultvaluetestschema.impl.db.DefaultValueTestGraphImpl.class);
		setVertexImplementationClass(de.uni_koblenz.jgralabtest.schemas.defaultvaluetestschema.TestVertex.VC, de.uni_koblenz.jgralabtest.schemas.defaultvaluetestschema.impl.db.TestVertexImpl.class);
		setVertexImplementationClass(de.uni_koblenz.jgralabtest.schemas.defaultvaluetestschema.TestSubVertex.VC, de.uni_koblenz.jgralabtest.schemas.defaultvaluetestschema.impl.db.TestSubVertexImpl.class);
		setEdgeImplementationClass(de.uni_koblenz.jgralabtest.schemas.defaultvaluetestschema.TestEdge.EC, de.uni_koblenz.jgralabtest.schemas.defaultvaluetestschema.impl.db.TestEdgeImpl.class);
	}
}
