/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralabtest.schemas.gretl.copy;

public interface CopyVertex extends de.uni_koblenz.jgralab.Vertex {

	public static final de.uni_koblenz.jgralab.schema.VertexClass VC = de.uni_koblenz.jgralabtest.schemas.gretl.copy.CopySchema.instance().vc_CopyVertex;

	public java.lang.String get_name();

	public void set_name(java.lang.String _name);

	public int get_uid();

	public void set_uid(int _uid);

	/**
	 * @return the next de.uni_koblenz.jgralabtest.schemas.gretl.copy.CopyVertex vertex in the global vertex sequence
	 */
	public de.uni_koblenz.jgralabtest.schemas.gretl.copy.CopyVertex getNextCopyVertex();
}
