/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.grumlschema.structure;

import de.uni_koblenz.jgralab.EdgeDirection;

import de.uni_koblenz.jgralab.grumlschema.structure.Attribute;
import de.uni_koblenz.jgralab.grumlschema.structure.AttributedElementClass;
/**
 * FromVertexClass: structure.AttributedElementClass
 * FromRoleName : 
 * ToVertexClass: structure.Attribute
 * ToRoleName : attribute
 */

public interface HasAttribute extends de.uni_koblenz.jgralab.Edge {

	public static final de.uni_koblenz.jgralab.schema.EdgeClass EC = de.uni_koblenz.jgralab.grumlschema.GrumlSchema.instance().ec_structure_HasAttribute;

	/**
	 * @return the next de.uni_koblenz.jgralab.grumlschema.structure.HasAttribute edge in the global edge sequence
	 */
	public de.uni_koblenz.jgralab.grumlschema.structure.HasAttribute getNextHasAttributeInGraph();

	/**
	 * @return the next edge of class de.uni_koblenz.jgralab.grumlschema.structure.HasAttribute at the "this" vertex
	 */
	public de.uni_koblenz.jgralab.grumlschema.structure.HasAttribute getNextHasAttributeIncidence();

	/**
	 * @return the next edge of class de.uni_koblenz.jgralab.grumlschema.structure.HasAttribute at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public de.uni_koblenz.jgralab.grumlschema.structure.HasAttribute getNextHasAttributeIncidence(EdgeDirection orientation);
	public AttributedElementClass getAlpha();
	public Attribute getOmega();
}
