/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.grumlschema.structure;

import de.uni_koblenz.jgralab.EdgeDirection;

public interface Package extends de.uni_koblenz.jgralab.grumlschema.structure.NamedElement {

	public static final de.uni_koblenz.jgralab.schema.VertexClass VC = de.uni_koblenz.jgralab.grumlschema.GrumlSchema.instance().vc_structure_Package;

	/**
	 * @return the next de.uni_koblenz.jgralab.grumlschema.structure.NamedElement vertex in the global vertex sequence
	 */
	public de.uni_koblenz.jgralab.grumlschema.structure.NamedElement getNextNamedElement();

	/**
	 * @return the next de.uni_koblenz.jgralab.grumlschema.structure.Package vertex in the global vertex sequence
	 */
	public de.uni_koblenz.jgralab.grumlschema.structure.Package getNextPackage();

	/**
	 * @return the first edge of class ContainsDefaultPackage at this vertex
	 */
	public de.uni_koblenz.jgralab.grumlschema.structure.ContainsDefaultPackage getFirstContainsDefaultPackageIncidence();

	/**
	 * @return the first edge of class ContainsDefaultPackage at this vertex
	 * @param orientation the orientation of the edge
	 */
	public de.uni_koblenz.jgralab.grumlschema.structure.ContainsDefaultPackage getFirstContainsDefaultPackageIncidence(EdgeDirection orientation);

	/**
	 * @return the first edge of class ContainsDomain at this vertex
	 */
	public de.uni_koblenz.jgralab.grumlschema.structure.ContainsDomain getFirstContainsDomainIncidence();

	/**
	 * @return the first edge of class ContainsDomain at this vertex
	 * @param orientation the orientation of the edge
	 */
	public de.uni_koblenz.jgralab.grumlschema.structure.ContainsDomain getFirstContainsDomainIncidence(EdgeDirection orientation);

	/**
	 * @return the first edge of class ContainsGraphElementClass at this vertex
	 */
	public de.uni_koblenz.jgralab.grumlschema.structure.ContainsGraphElementClass getFirstContainsGraphElementClassIncidence();

	/**
	 * @return the first edge of class ContainsGraphElementClass at this vertex
	 * @param orientation the orientation of the edge
	 */
	public de.uni_koblenz.jgralab.grumlschema.structure.ContainsGraphElementClass getFirstContainsGraphElementClassIncidence(EdgeDirection orientation);

	/**
	 * @return the first edge of class ContainsSubPackage at this vertex
	 */
	public de.uni_koblenz.jgralab.grumlschema.structure.ContainsSubPackage getFirstContainsSubPackageIncidence();

	/**
	 * @return the first edge of class ContainsSubPackage at this vertex
	 * @param orientation the orientation of the edge
	 */
	public de.uni_koblenz.jgralab.grumlschema.structure.ContainsSubPackage getFirstContainsSubPackageIncidence(EdgeDirection orientation);
		/**
		 * adds the given vertex as <code>subpackage</code> to this vertex, i.e. creates an
		 * <code>de.uni_koblenz.jgralab.grumlschema.structure.ContainsSubPackage</code> edge from this vertex to the given 
		 * one and returns the created edge.
		 * @return  a newly created edge of type <code>de.uni_koblenz.jgralab.grumlschema.structure.ContainsSubPackage</code>
		 *          between this vertex and the given one.
		 */
		public de.uni_koblenz.jgralab.grumlschema.structure.ContainsSubPackage add_subpackage(de.uni_koblenz.jgralab.grumlschema.structure.Package vertex);
		/**
		 * removes all subpackage adjacences to all vertices by 
		 * deleting the <code>de.uni_koblenz.jgralab.grumlschema.structure.ContainsSubPackage</code> edges of this vertex to 
		 * all other ones, but doesn't delete those vertices.
		 *
		 * @return the adjacent vertices prior to removal of incidences
		 */
		public java.util.List<? extends de.uni_koblenz.jgralab.grumlschema.structure.Package> remove_subpackage();
		/**
		 * removes the given vertex as <code>subpackage</code> from this vertex, i.e. 
		 * deletes the <code>de.uni_koblenz.jgralab.grumlschema.structure.ContainsSubPackage</code> edge connections of this vertex with 
		 * the given one.
		 */
		public boolean remove_subpackage(de.uni_koblenz.jgralab.grumlschema.structure.Package vertex);
		/**
		 * @return an Iterable of all vertices adjacent to this one with the rolename 'subpackage'
		 *         (connected with a <code>de.uni_koblenz.jgralab.grumlschema.structure.ContainsSubPackage</code> edge).
		 */
		public Iterable<? extends de.uni_koblenz.jgralab.grumlschema.structure.Package> get_subpackage();
		/**
		 * adds the given vertex as <code>comment</code> to this vertex, i.e. creates an
		 * <code>de.uni_koblenz.jgralab.grumlschema.structure.Annotates</code> edge from this vertex to the given 
		 * one and returns the created edge.
		 * @return  a newly created edge of type <code>de.uni_koblenz.jgralab.grumlschema.structure.Annotates</code>
		 *          between this vertex and the given one.
		 */
		public de.uni_koblenz.jgralab.grumlschema.structure.Annotates add_comment(de.uni_koblenz.jgralab.grumlschema.structure.Comment vertex);
		/**
		 * removes all comment adjacences to all vertices by 
		 * deleting the <code>de.uni_koblenz.jgralab.grumlschema.structure.Annotates</code> edges of this vertex to 
		 * all other ones, but doesn't delete those vertices.
		 *
		 * @return the adjacent vertices prior to removal of incidences
		 */
		public java.util.List<? extends de.uni_koblenz.jgralab.grumlschema.structure.Comment> remove_comment();
		/**
		 * removes the given vertex as <code>comment</code> from this vertex, i.e. 
		 * deletes the <code>de.uni_koblenz.jgralab.grumlschema.structure.Annotates</code> edge connections of this vertex with 
		 * the given one.
		 */
		public boolean remove_comment(de.uni_koblenz.jgralab.grumlschema.structure.Comment vertex);
		/**
		 * @return an Iterable of all vertices adjacent to this one with the rolename 'comment'
		 *         (connected with a <code>de.uni_koblenz.jgralab.grumlschema.structure.Annotates</code> edge).
		 */
		public Iterable<? extends de.uni_koblenz.jgralab.grumlschema.structure.Comment> get_comment();

	/**
	 * Returns an Iterable for all incidence edges of this vertex that are of type ContainsDefaultPackage or subtypes.
	 */
	public Iterable<de.uni_koblenz.jgralab.grumlschema.structure.ContainsDefaultPackage> getContainsDefaultPackageIncidences();
	
	/**
	 * Returns an Iterable for all incidence edges of this vertex that are of type ContainsDefaultPackage.
	 * @param direction EdgeDirection.IN or EdgeDirection.OUT, only edges of this direction will be included in the Iterable
	 */
	public Iterable<de.uni_koblenz.jgralab.grumlschema.structure.ContainsDefaultPackage> getContainsDefaultPackageIncidences(EdgeDirection direction);

	/**
	 * Returns an Iterable for all incidence edges of this vertex that are of type ContainsDomain or subtypes.
	 */
	public Iterable<de.uni_koblenz.jgralab.grumlschema.structure.ContainsDomain> getContainsDomainIncidences();
	
	/**
	 * Returns an Iterable for all incidence edges of this vertex that are of type ContainsDomain.
	 * @param direction EdgeDirection.IN or EdgeDirection.OUT, only edges of this direction will be included in the Iterable
	 */
	public Iterable<de.uni_koblenz.jgralab.grumlschema.structure.ContainsDomain> getContainsDomainIncidences(EdgeDirection direction);

	/**
	 * Returns an Iterable for all incidence edges of this vertex that are of type ContainsGraphElementClass or subtypes.
	 */
	public Iterable<de.uni_koblenz.jgralab.grumlschema.structure.ContainsGraphElementClass> getContainsGraphElementClassIncidences();
	
	/**
	 * Returns an Iterable for all incidence edges of this vertex that are of type ContainsGraphElementClass.
	 * @param direction EdgeDirection.IN or EdgeDirection.OUT, only edges of this direction will be included in the Iterable
	 */
	public Iterable<de.uni_koblenz.jgralab.grumlschema.structure.ContainsGraphElementClass> getContainsGraphElementClassIncidences(EdgeDirection direction);

	/**
	 * Returns an Iterable for all incidence edges of this vertex that are of type ContainsSubPackage or subtypes.
	 */
	public Iterable<de.uni_koblenz.jgralab.grumlschema.structure.ContainsSubPackage> getContainsSubPackageIncidences();
	
	/**
	 * Returns an Iterable for all incidence edges of this vertex that are of type ContainsSubPackage.
	 * @param direction EdgeDirection.IN or EdgeDirection.OUT, only edges of this direction will be included in the Iterable
	 */
	public Iterable<de.uni_koblenz.jgralab.grumlschema.structure.ContainsSubPackage> getContainsSubPackageIncidences(EdgeDirection direction);
}
