/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralabtest.schemas.algolib.simple.impl.std;

import de.uni_koblenz.jgralab.impl.GraphFactoryImpl;

import de.uni_koblenz.jgralab.ImplementationType;

import de.uni_koblenz.jgralabtest.schemas.algolib.simple.SimpleGraphFactory;

public class SimpleGraphFactoryImpl extends GraphFactoryImpl implements SimpleGraphFactory {

	public SimpleGraphFactoryImpl() {
		super(de.uni_koblenz.jgralabtest.schemas.algolib.simple.SimpleSchema.instance(), ImplementationType.STANDARD);
		createMaps();
		setGraphImplementationClass(de.uni_koblenz.jgralabtest.schemas.algolib.simple.SimpleGraph.GC, de.uni_koblenz.jgralabtest.schemas.algolib.simple.impl.std.SimpleGraphImpl.class);
		setVertexImplementationClass(de.uni_koblenz.jgralabtest.schemas.algolib.simple.SimpleVertex.VC, de.uni_koblenz.jgralabtest.schemas.algolib.simple.impl.std.SimpleVertexImpl.class);
		setEdgeImplementationClass(de.uni_koblenz.jgralabtest.schemas.algolib.simple.SimpleEdge.EC, de.uni_koblenz.jgralabtest.schemas.algolib.simple.impl.std.SimpleEdgeImpl.class);
	}
}
