/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralabtest.schemas.motorwaymap.impl.db;

import de.uni_koblenz.jgralab.impl.db.ReversedEdgeImpl;
import de.uni_koblenz.jgralab.impl.db.EdgeImpl;

import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.Graph;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;

import de.uni_koblenz.jgralabtest.schemas.motorwaymap.Motorway;
import de.uni_koblenz.jgralabtest.schemas.motorwaymap.StoppingPlace;

import java.io.IOException;

public class ReversedOffersImpl extends ReversedEdgeImpl implements de.uni_koblenz.jgralab.Edge, de.uni_koblenz.jgralabtest.schemas.motorwaymap.Offers {

	ReversedOffersImpl(EdgeImpl e, Graph g) {
		super(e, g);
	}

	@Override
	public final de.uni_koblenz.jgralab.schema.EdgeClass getAttributedElementClass() {
		return getNormalEdge().getAttributedElementClass();
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
		throw new GraphIOException("Can not call readAttributeValues for reversed Edges.");
	}

	public void readAttributeValueFromString(String attributeName, String value) throws GraphIOException {
		throw new GraphIOException("Can not call readAttributeValuesFromString for reversed Edges.");
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
		throw new GraphIOException("Can not call writeAttributeValues for reversed Edges.");
	}

	public String writeAttributeValueToString(String _attributeName) throws IOException, GraphIOException {
		throw new GraphIOException("Can not call writeAttributeValueToString for reversed Edges.");
	}

	public de.uni_koblenz.jgralabtest.schemas.motorwaymap.Offers getNextOffersInGraph() {
		return ((de.uni_koblenz.jgralabtest.schemas.motorwaymap.Offers)normalEdge).getNextOffersInGraph();
	}

	public de.uni_koblenz.jgralabtest.schemas.motorwaymap.Offers getNextOffersIncidence() {
		return (de.uni_koblenz.jgralabtest.schemas.motorwaymap.Offers)getNextIncidence(de.uni_koblenz.jgralabtest.schemas.motorwaymap.Offers.class);
	}

	public de.uni_koblenz.jgralabtest.schemas.motorwaymap.Offers getNextOffersIncidence(EdgeDirection orientation) {
		return (de.uni_koblenz.jgralabtest.schemas.motorwaymap.Offers)getNextIncidence(de.uni_koblenz.jgralabtest.schemas.motorwaymap.Offers.class, orientation);
	}
	public Motorway getAlpha() {
		return (Motorway) super.getAlpha();
	}
	public StoppingPlace getOmega() {
		return (StoppingPlace) super.getOmega();
	}
}
