/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralabtest.schemas.jniclient;

public interface JniTestGraph extends de.uni_koblenz.jgralab.Graph {

	public static final de.uni_koblenz.jgralab.schema.GraphClass GC = de.uni_koblenz.jgralabtest.schemas.jniclient.JniTestSchema.instance().gc_JniTestGraph;

	// ------------------------ Code for Link ------------------------

	/**
	 * @return the first Link edge in this graph
	 */
	public de.uni_koblenz.jgralabtest.schemas.jniclient.Link getFirstLink();

	/**
	 * Creates a new Link edge in this graph.
	 *
	 * @param alpha the start vertex of the edge
	 * @param omega the target vertex of the edge
	*/
	public de.uni_koblenz.jgralabtest.schemas.jniclient.Link createLink(de.uni_koblenz.jgralabtest.schemas.jniclient.Node alpha, de.uni_koblenz.jgralabtest.schemas.jniclient.Node omega);

	// ------------------------ Code for Node ------------------------

	/**
	 * @return the first Node vertex in this graph
	 */
	public de.uni_koblenz.jgralabtest.schemas.jniclient.Node getFirstNode();

	/**
	 * Creates a new Node vertex in this graph.
	 *
	*/
	public de.uni_koblenz.jgralabtest.schemas.jniclient.Node createNode();

	// ------------------------ Code for SimpleEdge ------------------------

	/**
	 * @return the first SimpleEdge edge in this graph
	 */
	public de.uni_koblenz.jgralabtest.schemas.jniclient.SimpleEdge getFirstSimpleEdge();

	/**
	 * Creates a new SimpleEdge edge in this graph.
	 *
	 * @param alpha the start vertex of the edge
	 * @param omega the target vertex of the edge
	*/
	public de.uni_koblenz.jgralabtest.schemas.jniclient.SimpleEdge createSimpleEdge(de.uni_koblenz.jgralabtest.schemas.jniclient.SimpleNode alpha, de.uni_koblenz.jgralabtest.schemas.jniclient.SimpleNode omega);

	// ------------------------ Code for SimpleNode ------------------------

	/**
	 * @return the first SimpleNode vertex in this graph
	 */
	public de.uni_koblenz.jgralabtest.schemas.jniclient.SimpleNode getFirstSimpleNode();

	/**
	 * Creates a new SimpleNode vertex in this graph.
	 *
	*/
	public de.uni_koblenz.jgralabtest.schemas.jniclient.SimpleNode createSimpleNode();

	/**
	 * @return an Iterable for all edges of this graph that are of type SimpleEdge or subtypes.
	 */
	public Iterable<de.uni_koblenz.jgralabtest.schemas.jniclient.SimpleEdge> getSimpleEdgeEdges();
	

	/**
	 * @return an Iterable for all edges of this graph that are of type Link or subtypes.
	 */
	public Iterable<de.uni_koblenz.jgralabtest.schemas.jniclient.Link> getLinkEdges();
	

	/**
	 * @return an Iterable for all vertices of this graph that are of type SimpleNode or subtypes.
	 */
	public Iterable<de.uni_koblenz.jgralabtest.schemas.jniclient.SimpleNode> getSimpleNodeVertices();
	

	/**
	 * @return an Iterable for all vertices of this graph that are of type Node or subtypes.
	 */
	public Iterable<de.uni_koblenz.jgralabtest.schemas.jniclient.Node> getNodeVertices();
	
}
