/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.grumlschema.domains;

import de.uni_koblenz.jgralab.EdgeDirection;

public interface MapDomain extends de.uni_koblenz.jgralab.grumlschema.domains.Domain {

	public static final de.uni_koblenz.jgralab.schema.VertexClass VC = de.uni_koblenz.jgralab.grumlschema.GrumlSchema.instance().vc_domains_MapDomain;

	/**
	 * @return the next de.uni_koblenz.jgralab.grumlschema.domains.Domain vertex in the global vertex sequence
	 */
	public de.uni_koblenz.jgralab.grumlschema.domains.Domain getNextDomain();

	/**
	 * @return the next de.uni_koblenz.jgralab.grumlschema.domains.MapDomain vertex in the global vertex sequence
	 */
	public de.uni_koblenz.jgralab.grumlschema.domains.MapDomain getNextMapDomain();

	/**
	 * @return the next de.uni_koblenz.jgralab.grumlschema.structure.NamedElement vertex in the global vertex sequence
	 */
	public de.uni_koblenz.jgralab.grumlschema.structure.NamedElement getNextNamedElement();

	/**
	 * @return the first edge of class HasValueDomain at this vertex
	 */
	public de.uni_koblenz.jgralab.grumlschema.domains.HasValueDomain getFirstHasValueDomainIncidence();

	/**
	 * @return the first edge of class HasValueDomain at this vertex
	 * @param orientation the orientation of the edge
	 */
	public de.uni_koblenz.jgralab.grumlschema.domains.HasValueDomain getFirstHasValueDomainIncidence(EdgeDirection orientation);

	/**
	 * @return the first edge of class HasKeyDomain at this vertex
	 */
	public de.uni_koblenz.jgralab.grumlschema.domains.HasKeyDomain getFirstHasKeyDomainIncidence();

	/**
	 * @return the first edge of class HasKeyDomain at this vertex
	 * @param orientation the orientation of the edge
	 */
	public de.uni_koblenz.jgralab.grumlschema.domains.HasKeyDomain getFirstHasKeyDomainIncidence(EdgeDirection orientation);
		/**
		 * adds the given vertex as <code>comment</code> to this vertex, i.e. creates an
		 * <code>de.uni_koblenz.jgralab.grumlschema.structure.Annotates</code> edge from this vertex to the given 
		 * one and returns the created edge.
		 * @return  a newly created edge of type <code>de.uni_koblenz.jgralab.grumlschema.structure.Annotates</code>
		 *          between this vertex and the given one.
		 */
		public de.uni_koblenz.jgralab.grumlschema.structure.Annotates add_comment(de.uni_koblenz.jgralab.grumlschema.structure.Comment vertex);
		/**
		 * removes all comment adjacences to all vertices by 
		 * deleting the <code>de.uni_koblenz.jgralab.grumlschema.structure.Annotates</code> edges of this vertex to 
		 * all other ones, but doesn't delete those vertices.
		 *
		 * @return the adjacent vertices prior to removal of incidences
		 */
		public java.util.List<? extends de.uni_koblenz.jgralab.grumlschema.structure.Comment> remove_comment();
		/**
		 * removes the given vertex as <code>comment</code> from this vertex, i.e. 
		 * deletes the <code>de.uni_koblenz.jgralab.grumlschema.structure.Annotates</code> edge connections of this vertex with 
		 * the given one.
		 */
		public boolean remove_comment(de.uni_koblenz.jgralab.grumlschema.structure.Comment vertex);
		/**
		 * @return an Iterable of all vertices adjacent to this one with the rolename 'comment'
		 *         (connected with a <code>de.uni_koblenz.jgralab.grumlschema.structure.Annotates</code> edge).
		 */
		public Iterable<? extends de.uni_koblenz.jgralab.grumlschema.structure.Comment> get_comment();
		/**
		 * adds the given vertex as <code>keydomain</code> to this vertex, i.e. creates an
		 * <code>de.uni_koblenz.jgralab.grumlschema.domains.HasKeyDomain</code> edge from this vertex to the given 
		 * one and returns the created edge.
		 * @return  a newly created edge of type <code>de.uni_koblenz.jgralab.grumlschema.domains.HasKeyDomain</code>
		 *          between this vertex and the given one.
		 */
		public de.uni_koblenz.jgralab.grumlschema.domains.HasKeyDomain add_keydomain(de.uni_koblenz.jgralab.grumlschema.domains.Domain vertex);
		/**
		 * removes all keydomain adjacences to all vertices by 
		 * deleting the <code>de.uni_koblenz.jgralab.grumlschema.domains.HasKeyDomain</code> edges of this vertex to 
		 * all other ones, but doesn't delete those vertices.
		 *
		 * @return the adjacent vertices prior to removal of incidences
		 */
		public java.util.List<? extends de.uni_koblenz.jgralab.grumlschema.domains.Domain> remove_keydomain();
		/**
		 * removes the given vertex as <code>keydomain</code> from this vertex, i.e. 
		 * deletes the <code>de.uni_koblenz.jgralab.grumlschema.domains.HasKeyDomain</code> edge connections of this vertex with 
		 * the given one.
		 */
		public boolean remove_keydomain(de.uni_koblenz.jgralab.grumlschema.domains.Domain vertex);
		/**
		 * @return the vertex to this one with the rolename 'keydomain' 
		 *         (connected with a <code>de.uni_koblenz.jgralab.grumlschema.domains.HasKeyDomain</code> edge), or null if no such vertex exists
		 */
		public de.uni_koblenz.jgralab.grumlschema.domains.Domain get_keydomain();
		/**
		 * adds the given vertex as <code>valuedomain</code> to this vertex, i.e. creates an
		 * <code>de.uni_koblenz.jgralab.grumlschema.domains.HasValueDomain</code> edge from this vertex to the given 
		 * one and returns the created edge.
		 * @return  a newly created edge of type <code>de.uni_koblenz.jgralab.grumlschema.domains.HasValueDomain</code>
		 *          between this vertex and the given one.
		 */
		public de.uni_koblenz.jgralab.grumlschema.domains.HasValueDomain add_valuedomain(de.uni_koblenz.jgralab.grumlschema.domains.Domain vertex);
		/**
		 * removes all valuedomain adjacences to all vertices by 
		 * deleting the <code>de.uni_koblenz.jgralab.grumlschema.domains.HasValueDomain</code> edges of this vertex to 
		 * all other ones, but doesn't delete those vertices.
		 *
		 * @return the adjacent vertices prior to removal of incidences
		 */
		public java.util.List<? extends de.uni_koblenz.jgralab.grumlschema.domains.Domain> remove_valuedomain();
		/**
		 * removes the given vertex as <code>valuedomain</code> from this vertex, i.e. 
		 * deletes the <code>de.uni_koblenz.jgralab.grumlschema.domains.HasValueDomain</code> edge connections of this vertex with 
		 * the given one.
		 */
		public boolean remove_valuedomain(de.uni_koblenz.jgralab.grumlschema.domains.Domain vertex);
		/**
		 * @return the vertex to this one with the rolename 'valuedomain' 
		 *         (connected with a <code>de.uni_koblenz.jgralab.grumlschema.domains.HasValueDomain</code> edge), or null if no such vertex exists
		 */
		public de.uni_koblenz.jgralab.grumlschema.domains.Domain get_valuedomain();

	/**
	 * Returns an Iterable for all incidence edges of this vertex that are of type HasValueDomain or subtypes.
	 */
	public Iterable<de.uni_koblenz.jgralab.grumlschema.domains.HasValueDomain> getHasValueDomainIncidences();
	
	/**
	 * Returns an Iterable for all incidence edges of this vertex that are of type HasValueDomain.
	 * @param direction EdgeDirection.IN or EdgeDirection.OUT, only edges of this direction will be included in the Iterable
	 */
	public Iterable<de.uni_koblenz.jgralab.grumlschema.domains.HasValueDomain> getHasValueDomainIncidences(EdgeDirection direction);

	/**
	 * Returns an Iterable for all incidence edges of this vertex that are of type HasKeyDomain or subtypes.
	 */
	public Iterable<de.uni_koblenz.jgralab.grumlschema.domains.HasKeyDomain> getHasKeyDomainIncidences();
	
	/**
	 * Returns an Iterable for all incidence edges of this vertex that are of type HasKeyDomain.
	 * @param direction EdgeDirection.IN or EdgeDirection.OUT, only edges of this direction will be included in the Iterable
	 */
	public Iterable<de.uni_koblenz.jgralab.grumlschema.domains.HasKeyDomain> getHasKeyDomainIncidences(EdgeDirection direction);
}
