/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralabtest.schemas.citymap.impl.std;

import de.uni_koblenz.jgralab.impl.GraphFactoryImpl;

import de.uni_koblenz.jgralab.ImplementationType;

import de.uni_koblenz.jgralabtest.schemas.citymap.CityMapFactory;

public class CityMapFactoryImpl extends GraphFactoryImpl implements CityMapFactory {

	public CityMapFactoryImpl() {
		super(de.uni_koblenz.jgralabtest.schemas.citymap.CityMapSchema.instance(), ImplementationType.STANDARD);
		createMaps();
		setGraphImplementationClass(de.uni_koblenz.jgralabtest.schemas.citymap.CityMap.GC, de.uni_koblenz.jgralabtest.schemas.citymap.impl.std.CityMapImpl.class);
		setVertexImplementationClass(de.uni_koblenz.jgralabtest.schemas.citymap.Intersection.VC, de.uni_koblenz.jgralabtest.schemas.citymap.impl.std.IntersectionImpl.class);
		setVertexImplementationClass(de.uni_koblenz.jgralabtest.schemas.citymap.CarPark.VC, de.uni_koblenz.jgralabtest.schemas.citymap.impl.std.CarParkImpl.class);
		setVertexImplementationClass(de.uni_koblenz.jgralabtest.schemas.citymap.ParkingGarage.VC, de.uni_koblenz.jgralabtest.schemas.citymap.impl.std.ParkingGarageImpl.class);
		setEdgeImplementationClass(de.uni_koblenz.jgralabtest.schemas.citymap.Footpath.EC, de.uni_koblenz.jgralabtest.schemas.citymap.impl.std.FootpathImpl.class);
		setEdgeImplementationClass(de.uni_koblenz.jgralabtest.schemas.citymap.Street.EC, de.uni_koblenz.jgralabtest.schemas.citymap.impl.std.StreetImpl.class);
		setEdgeImplementationClass(de.uni_koblenz.jgralabtest.schemas.citymap.Bridge.EC, de.uni_koblenz.jgralabtest.schemas.citymap.impl.std.BridgeImpl.class);
	}
}
