/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simplerdbms;

import de.uni_koblenz.jgralab.EdgeDirection;

import de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simplerdbms.ForeignKey;
import de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simplerdbms.Table;
/**
 * FromVertexClass: Table
 * FromRoleName : 
 * ToVertexClass: ForeignKey
 * ToRoleName : foreignKey
 */

public interface HasForeignKey extends de.uni_koblenz.jgralab.Edge {

	public static final de.uni_koblenz.jgralab.schema.EdgeClass EC = de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simplerdbms.SimpleRDBMSSchema.instance().ec_HasForeignKey;

	/**
	 * @return the next de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simplerdbms.HasForeignKey edge in the global edge sequence
	 */
	public de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simplerdbms.HasForeignKey getNextHasForeignKeyInGraph();

	/**
	 * @return the next edge of class de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simplerdbms.HasForeignKey at the "this" vertex
	 */
	public de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simplerdbms.HasForeignKey getNextHasForeignKeyIncidence();

	/**
	 * @return the next edge of class de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simplerdbms.HasForeignKey at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public de.uni_koblenz.jgralabtest.schemas.gretl.qvt.simplerdbms.HasForeignKey getNextHasForeignKeyIncidence(EdgeDirection orientation);
	public Table getAlpha();
	public ForeignKey getOmega();
}
