/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralabtest.schemas.gretl.varro.impl.std.uml;

import de.uni_koblenz.jgralab.impl.IncidenceIterable;

import de.uni_koblenz.jgralab.impl.std.VertexImpl;

import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;
import de.uni_koblenz.jgralab.NoSuchAttributeException;

import java.io.IOException;

public class ClassImpl extends VertexImpl implements de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.NamedElement {

	protected java.lang.String _name;

	public ClassImpl(int id, de.uni_koblenz.jgralab.Graph g) {
		super(id, g);
	}

	@Override
	public final de.uni_koblenz.jgralab.schema.VertexClass getAttributedElementClass() {
		return de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class.VC;
	}

	@Override
	public final java.lang.Class<? extends de.uni_koblenz.jgralab.Vertex> getSchemaClass() {
		return de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class.class;
	}

	@SuppressWarnings("unchecked")
	public <T> T getAttribute(String attributeName) {
		if (attributeName.equals("name")) return (T) get_name();
		throw new NoSuchAttributeException("uml.Class doesn't contain an attribute " + attributeName);
	}

	public <T> void setAttribute(String attributeName, T data) {
		if (attributeName.equals("name")) {
			set_name((java.lang.String) data);
			return;
		}
		throw new NoSuchAttributeException("uml.Class doesn't contain an attribute " + attributeName);
	}

	public java.lang.String get_name() {
		return _name;
	}

	public void set_name(java.lang.String _name) {
		ecaAttributeChanging("name", this._name, _name);
		Object oldValue = this._name;
		this._name = _name;
		graphModified();
	ecaAttributeChanged("name", oldValue, _name);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
		_name = io.matchUtfString();
		set_name(_name);
	}

	public void readAttributeValueFromString(String attributeName, String value) throws GraphIOException {
		if (attributeName.equals("name")) {
			GraphIO io = GraphIO.createStringReader(value, getSchema());
			_name = io.matchUtfString();
			set_name(_name);
			return;
		}
		throw new NoSuchAttributeException("uml.Class doesn't contain an attribute " + attributeName);
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
		io.space();
		io.writeUtfString(_name);
	}

	public String writeAttributeValueToString(String attributeName) throws IOException, GraphIOException {
		if (attributeName.equals("name")) {
			GraphIO io = GraphIO.createStringWriter(getSchema());
			io.writeUtfString(_name);
			return io.getStringWriterResult();
		}
		throw new NoSuchAttributeException("uml.Class doesn't contain an attribute " + attributeName);
	}

	@Override
	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class getNextClass() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class)getNextVertex(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class.class);
	}

	@Override
	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.NamedElement getNextNamedElement() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.NamedElement)getNextVertex(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.NamedElement.class);
	}

	@Override
	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass getFirstContainsClassIncidence() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass)getFirstIncidence(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass.class);
	}

	@Override
	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass getFirstContainsClassIncidence(EdgeDirection orientation) {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass)getFirstIncidence(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass.class, orientation);
	}

	@Override
	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType getFirstHasTypeIncidence() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType)getFirstIncidence(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType.class);
	}

	@Override
	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType getFirstHasTypeIncidence(EdgeDirection orientation) {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType)getFirstIncidence(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType.class, orientation);
	}

	@Override
	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub getFirstHasSubIncidence() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub)getFirstIncidence(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub.class);
	}

	@Override
	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub getFirstHasSubIncidence(EdgeDirection orientation) {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub)getFirstIncidence(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub.class, orientation);
	}

	@Override
	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper getFirstHasSuperIncidence() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper)getFirstIncidence(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper.class);
	}

	@Override
	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper getFirstHasSuperIncidence(EdgeDirection orientation) {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper)getFirstIncidence(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper.class, orientation);
	}

	@Override
	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute getFirstHasAttributeIncidence() {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute)getFirstIncidence(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute.class);
	}

	@Override
	public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute getFirstHasAttributeIncidence(EdgeDirection orientation) {
		return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute)getFirstIncidence(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute.class, orientation);
	}
		@Override
		public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute add_feature(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute vertex) {
			return ((de.uni_koblenz.jgralabtest.schemas.gretl.varro.UMLGraph)getGraph()).createEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute.EC, (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class) this, (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute) vertex);
		}
		@Override
		public java.util.List<? extends de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute> remove_feature() {
			java.util.List<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute> adjacences = new java.util.ArrayList<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute>();
			de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute edge = (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute) getFirstIncidence(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute.class, EdgeDirection.OUT);
			while (edge != null) {
				de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute next = (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute) edge.getNextIncidence(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute.class, EdgeDirection.OUT);
				adjacences.add((de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute) edge.getThat());
				edge.delete();
				edge = next;
			}
			return adjacences;
		}
		@Override
		public boolean remove_feature(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute vertex) {
			boolean elementRemoved = false;
			de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute edge = (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute) getFirstIncidence(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute.class, EdgeDirection.OUT);
			while (edge != null) {
				de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute next = (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute) edge.getNextIncidence(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute.class, EdgeDirection.OUT);
				if (edge.getThat().equals(vertex)) {			edge.delete();
					elementRemoved = true;
				}
				edge = next;
			}
			return elementRemoved;
		}
		@Override
		public Iterable<? extends de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute> get_feature() {
			return new de.uni_koblenz.jgralab.impl.NeighbourIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Attribute>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute.class, EdgeDirection.OUT);
		}
		@Override
		public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass add_elemOwner(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package vertex) {
			return ((de.uni_koblenz.jgralabtest.schemas.gretl.varro.UMLGraph)getGraph()).createEdge(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass.EC, (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package) vertex, (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Class) this);
		}
		@Override
		public java.util.List<? extends de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package> remove_elemOwner() {
			java.util.List<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package> adjacences = new java.util.ArrayList<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package>();
			de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass edge = (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass) getFirstIncidence(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass.class, EdgeDirection.IN);
			while (edge != null) {
				de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass next = (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass) edge.getNextIncidence(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass.class, EdgeDirection.IN);
				adjacences.add((de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package) edge.getThat());
				edge.delete();
				edge = next;
			}
			return adjacences;
		}
		@Override
		public boolean remove_elemOwner(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package vertex) {
			boolean elementRemoved = false;
			de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass edge = (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass) getFirstIncidence(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass.class, EdgeDirection.IN);
			while (edge != null) {
				de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass next = (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass) edge.getNextIncidence(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass.class, EdgeDirection.IN);
				if (edge.getThat().equals(vertex)) {			edge.delete();
					elementRemoved = true;
				}
				edge = next;
			}
			return elementRemoved;
		}
		@Override
		public de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package get_elemOwner() {
			de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass edge = (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass) getFirstIncidence(de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass.class, EdgeDirection.IN);
			if (edge != null) {
				return (de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.Package) edge.getThat();
			}
			return null;
		}

	@Override
	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass> getContainsClassIncidences() {
		return new IncidenceIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass.class);
	}
	
	@Override
	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass> getContainsClassIncidences(EdgeDirection direction) {
		return new IncidenceIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.ContainsClass.class, direction);
	}

	@Override
	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType> getHasTypeIncidences() {
		return new IncidenceIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType.class);
	}
	
	@Override
	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType> getHasTypeIncidences(EdgeDirection direction) {
		return new IncidenceIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasType.class, direction);
	}

	@Override
	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub> getHasSubIncidences() {
		return new IncidenceIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub.class);
	}
	
	@Override
	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub> getHasSubIncidences(EdgeDirection direction) {
		return new IncidenceIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSub.class, direction);
	}

	@Override
	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper> getHasSuperIncidences() {
		return new IncidenceIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper.class);
	}
	
	@Override
	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper> getHasSuperIncidences(EdgeDirection direction) {
		return new IncidenceIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasSuper.class, direction);
	}

	@Override
	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute> getHasAttributeIncidences() {
		return new IncidenceIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute.class);
	}
	
	@Override
	public Iterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute> getHasAttributeIncidences(EdgeDirection direction) {
		return new IncidenceIterable<de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute>(this, de.uni_koblenz.jgralabtest.schemas.gretl.varro.uml.HasAttribute.class, direction);
	}
}
